[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
FLASK_ENV = "@jinja {{ env.FLASK_ENV }}"
#EXTENSIONS = ["app.routes:init_app",]

[development]
DEBUG = true
FLASK_DEBUG = true
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.DATABASE_DEV_URI}}"


[production]
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.DATABASE_PROD_URI}}"

[testing]
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.DATABASE_TESTING_URI}}"